
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/springbatch
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
  batch:
    job:
      names: ${job.name:NONE}
            
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mybatis/mariadb/**/*.sqlx

---

spring:
  profiles: dev
    